// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using mas.Infra;

#nullable disable

namespace msa.Infra.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("msa.Domain.Aggregates.TradingCash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Adhoc")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("Advance")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("BankSaving")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("CashAmount")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("CreditLine")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("DebtInterest")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ExternalTransfer")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("FSaving")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("FSavingForPower")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("FSavingPower")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("FeeSum")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("InternalTransfer")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("IntradayDebt")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MatchedBuy")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MatchedBuyFee")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("PendingBuy")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("PendingBuyDebt")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("PendingBuyFee")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ReceivableDividend")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ReceivableMatureCW")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ReceivableOddlot")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ReceivableT0")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ReceivableT1")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ReceivableT2")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("RemainDebt")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("RemainSecuritiesPower")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("TradingCashs", (string)null);
                });

            modelBuilder.Entity("msa.Domain.Aggregates.TradingFeeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FeeType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long>("Value")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("TradingFeeItems", (string)null);
                });

            modelBuilder.Entity("msa.Domain.Aggregates.TradingSecuritiesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("Dividend")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ESOP")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ESOPWaiting")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("Holding")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("HoldingWaiting")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MarproSuspend")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MatchedBuyIntraday")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MatchedSellIntraday")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MatchedSellIntraday_Mar")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MortgageAtBank")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MortgageAtBankWaiting")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("OddlotSellIntraday")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("PendingSell")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("PendingSell_Mar")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ReceivableRight")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ReceivableT1")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("ReceivableT2")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("Restricted")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("RestrictedWaiting")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("TradingAvail")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("TradingAvail_Mar")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("TradingWaiting")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("WaitingFromCustody")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.ToTable("TradingSecuritiesItem", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
